### ISSUE TITLE
Xcode build crashes in Unity Cloud Build when adding a post-process build

### ISSUE THREAD

**Issue by MrVeit** [lupidan/apple-signin-unity#202]
Hello, when trying to build a project via Unity Cloud Build after [adding post build proccess](https://github.com/lupidan/apple-signin-unity?tab=readme-ov-file#programmatic-setup-with-a-script), the build crashes when compiling to xcode. 
I tried different configurations, the current Unity version in the project is 2021.3.22f, but due to the error "Can't Add Sign In With Apple programatically in this Unity version" I had to build in UCB on 2021 latest LTC and 2022 latest LTC with XCode version 15.0+, same result.

**Comment by LeshM** [comment]
Hey @MrVeit I'm facing exactly the same issue with 2021.2.25f.
Any luck fining a fix?

**Comment by lupidan** [comment]
Update to 1.4.3

https://github.com/lupidan/apple-signin-unity/releases/tag/v1.4.3

**Comment by MrVeit** [comment]
> Hey @MrVeit I'm facing exactly the same issue with 2021.2.25f. Any luck fining a fix?

Hi, unfortunately no, I have a similar problem on the current version as on the previous one. I don't know why the author closed this discussion :)

**Comment by MrVeit** [comment]
> Update to 1.4.3
> 
> https://github.com/lupidan/apple-signin-unity/releases/tag/v1.4.3

I am using the latest version of your plugin.
The project also has Appodeal, Firebase Analytics, Crashlytics and Unity Leaderboards + Unity Authorization sdk. 

I assume that there is some conflict in xcode at Unity Cloud Build service when building the project, but then it would not be built there initially, not only after adding Post proccess build function.

**Comment by lupidan** [comment]
You need to use the version present in this repository, version 1.4.3.

If for some reason you are using the version from the [Unity Asset Store](https://assetstore.unity.com/packages/tools/integration/sign-in-with-apple-unity-plugin-152088), that version is 1.4.2.

Unity rejected the Asset Store upgrade, because the name of the asset contains "Apple" in it 🤷‍♀️

<img width="1152" alt="Screenshot 2024-05-01 at 23 37 52" src="https://github.com/lupidan/apple-signin-unity/assets/1314521/6f60c634-4f9b-472c-8429-022ed871b22d">

**Comment by lupidan** [comment]
Good news
I retried sending the upgrade with some notes and 1.4.3 is also published in the Asset Store
