### ISSUE TITLE
App cannot start after signing

### ISSUE THREAD

**Issue by sunyajie0829** [lupidan/apple-signin-unity#70]
Unity 2018.4.12 F1 version. After exporting the Mac version of. App, it can run normally, but after signing, the app can't be opened. What's your wish? In addition, does the plug-in have any requirements for the version of unity?

**Comment by lupidan** [comment]
The plugin should work fine on that Unity version.
App signing is a real headache, it really depends on the piece of software you want to sign. **There is no unique way of doing it**.

My recommendation, make a script to codesign, **use a development certificate for it**, and start with no entitlements, try adding/removing entitlements, and attempt running. Basically add/remove one at a time until you figure out.

In any case, there is a manual with an example case that worked for me. **Just because it worked for me doesn't necessarily mean that it will work for you**, but it can give you some idea on how to tackle the issue.
https://github.com/lupidan/apple-signin-unity/blob/master/docs/macOS_NOTES.md

**Comment by sunyajie0829** [comment]
OK, I'll do it as you suggest and give feedback after success, thank you.
