### ISSUE TITLE
Question: How exactly do we login with the credentials?

### ISSUE THREAD

**Issue by rafaelf82** [lupidan/apple-signin-unity#78]
Your flow chart shows in 2 situations that if we have credentials we use those to login.

I'm a bit confused by how this happens...

In your sample you have this method:

```
    private void CheckCredentialStatusForUserId(string appleUserId)
    {
        // If there is an apple ID available, we should check the credential state
        this._appleAuthManager.GetCredentialState(
            appleUserId,
            state =>
            {
                switch (state)
                {
                    // If it's authorized, login with that user id
                    case CredentialState.Authorized:
                        this.SetupGameMenu(appleUserId, null);
                        return;
                    
                    // If it was revoked, or not found, we need a new sign in with apple attempt
                    // Discard previous apple user id
                    case CredentialState.Revoked:
                    case CredentialState.NotFound:
                        this.SetupLoginMenuForSignInWithApple();
                        PlayerPrefs.DeleteKey(AppleUserIdKey);
                        return;
                }
            },
            error =>
            {
                var authorizationErrorCode = error.GetAuthorizationErrorCode();
                Debug.LogWarning("Error while trying to get credential state " + authorizationErrorCode.ToString() + " " + error.ToString());
                this.SetupLoginMenuForSignInWithApple();
            });
    }
```
But I don't actually see how login happens after that...
You call SetupGameMenu which only prints values...

**Comment by SnnYsf** [comment]
I agree with you.
In this case, how do we make firebase re-login?


we need this again appleIdCredential = credential as IAppleIDCredential
I can not found this again


CheckCredentialStatusForUserId
Can you type in the following firebase login?

**Comment by lupidan** [comment]
> But I don't actually see how login happens after that...
You call SetupGameMenu which only prints values...

**This is a plugin to get Apple authentication credentials for your server**, that's why those are "just printed".

If those are printed, you did login with apple, and you obtained those credentials to **create a user in your system**.
After that, you should save the apple user ID in your device and, and from here on, validate it with `GetCredentialState`.
If the returned credential state is Authorized, **you know that apple user id is valid**, and you can use it on your system and grant the user access.

> In this case, how do we make firebase re-login?

This is not a plugin for a Firebase login.
**This is a plugin to get Apple authentication credentials for your server** (it can be Firebase, it can be Gamesparks, it can be your own server...)

I made a tentative guide on how Firebase and this Sign in With Apple plugin could work toghether [here](https://github.com/lupidan/apple-signin-unity/blob/master/docs/Firebase_NOTES.md), but again, Firebase is **not** the purpose of this plugin.
