### ISSUE TITLE
Only works the first time

### ISSUE THREAD

**Issue by erikblue88** [lupidan/apple-signin-unity#9]
Hi friends, I have tried this great plugin, I install it, configure it and run it. It works great, retreive ID, Name, email, etc., but when I logout and try login again it does not retreive the name nor the email, I tried to uninstall and install again but never retreive all data again.
I did some wrong? I need to do anything else?

**Comment by lupidan** [comment]
Ok, I have been testing.

As far as it looks, the name and email is only provided during the **first** Sign in with Apple.
Once that has happened, the next time the user tries to sign in with Apple, the popup will just ask if the user wants to reuse the credentials, but it will NOT receive the name and email. (Kind of like a Quick Login)

**This makes sense**, the first time you receive AppleID/Email/Name, your app should be responsible of creating the user in your server.
After that, if the user tries to login again, you only get the Apple ID, because the other data was given to you before.

If you want to re-get the name/email for testing purposes, you can revoke the credentials. Just go to `Settings` => `Click your iTunes user` => `Password & Security` => `Apple ID logins`. There you can select the app and click on `Stop using Apple ID`
This will effectively revoke the credentials, and next login you will get name and email.

**Comment by lupidan** [comment]
Let me know if this solves your question 👍

**Comment by erikblue88** [comment]
Hi @lupidan thank you very much for your answer.
Yes, it response perfectly my question.
