### ISSUE TITLE
Replace MonoBehaviour update loop with a better solution

### ISSUE THREAD

**Issue by IdoMarkovitz** [lupidan/apple-signin-unity#96]
You should really consider simplifying your implementation by using tasks and continuing them on the main thread. Much like Firebase does with Google Sign In... you can take a look at Firebase extension method ContinueWithOnMainThread:

https://firebase.google.com/docs/reference/unity/class/firebase/extensions/task-extension#class_firebase_1_1_extensions_1_1_task_extension_1af1fc309e7e9b9e9a3655b8b47cb06014

Facebook log in has a different solution (relies on the iOS life cycle events) which is also great:

https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle

There really is no reason that an extra MonoBehaviour (or that a MonoBehaviour) will be required to support the Sign in with apple process.

**Comment by lupidan** [comment]
This looks like a feature request, not an actual issue. That's what the Discussions tab is for. But let's discuss it here.

> You should really consider simplifying your implementation by using tasks and continuing them on the main thread. Much like Firebase does with Google Sign In... you can take a look at Firebase extension method ContinueWithOnMainThread:

Firebase **USES** a MonoBehaviour (`FirebaseMonoBehaviour`) to handle incoming async calls, at least according to my decompiler. `ContinueWithOnMainThread` is an extension method provided by the Firebase SDK that queues the calls in a `FirebaseHandler` class, and the handler class IS updated in the FirebaseMonoBehaviour, so callbacks are executed in the unity update loop.

On top of that, `Task` support was introduced in Unity 2018.1, so by using them, we would leave out old games that still rely on previous Unity versions

> Facebook log in has a different solution (relies on the iOS life cycle events) which is also great:

A quick decompiler look tells me a different story. Facebook **ALSO USES** MonoBehaviour classes.
When Facebook SDK is initialized, a class called `ComponentFactory` creates a GameObject and adds components to it. Then the Facebook SDK is probably using `UnitySendMessage` to call methods in the `FacebookGameObject` MonoBehaviour. This is, again, so callbacks are executed in the unity update loop.

> There really is no reason that an extra MonoBehaviour (or that a MonoBehaviour) will be required to support the Sign in with apple process.

That's why the Update method is in a manager class, and the plugin's code is **not** creating any GameObjects with `MonoBehaviour` components in your scene. With that in mind, you have the freedom to call it from whenever you want to call it, instead of forcing the creation of an unsolicited GameObject in your scene.

This approach gives flexibility to every project:
- You can go with the easy solution and just have it inside a dedicated MonoBehaviour
- You can add it to an already existing MonoBehaviour in your project that handles more systems
- If you use UniRx, you could add support for this system in an ITickable class

With that said, **a MonoBehaviour IS required**. Just because you don't see it, doesn't mean it's not using one under the hood.

If you need that `Task` support, you can always create a MonoBehaviour wrapper class that Updates an `AppleAuthManager` instance in its `Update` method, and create your async calls that yield until you get a result.

**Comment by IdoMarkovitz** [comment]
Thanks for the quick and detailed response!

You’re right I guess this is more of a feature request.

Perhaps I wasn’t clear. My issue was not that a MonoBehaviour is required, but rather that the usage of a MonoBehaviour could be abstracted from me (as was done with Google/Facebook) which helped with 2 things:

1. It allowed me to focus more on the actual log in implementation and not on how the plug-in handles asynchronous messaging which made it simpler (for me).

2. It didn’t add an extra step that developers that implement the log in can possibly miss.

**Comment by lupidan** [comment]
I see value in adding the suggested abstraction, however I am not a fan of creating unsolicited GameObjects with dedicated plugin MonoBehaviours. From my experience, this can get specially cumbersome when dealing with Editor tests, and scene loading.

That's why the plugin is offering the option to Update the manager from wherever the developer feels it's more appropiate, as I described in the previous post.

Also, the documentation clearly states how it should be set up. So I don't see it as a big inconvenience vs the flexibility it provides.

While I appreciate your suggestion, this is not something that I plan to support.
